name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: casestudy-455411

      - name: Configure Docker to use gcloud as a credential helper
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build backend Docker image
        run: |
          cd backend
          docker build -t us-central1-docker.pkg.dev/casestudy-455411/my-repo/backend:latest .

      - name: Build frontend Docker image
        run: |
          cd frontend
          docker build -t us-central1-docker.pkg.dev/casestudy-455411/my-repo/frontend:latest .

      - name: Push Docker images to Artifact Registry
        run: |
          docker push us-central1-docker.pkg.dev/casestudy-455411/my-repo/backend:latest
          docker push us-central1-docker.pkg.dev/casestudy-455411/my-repo/frontend:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy backend \
            --image us-central1-docker.pkg.dev/casestudy-455411/my-repo/backend:latest \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated

          gcloud run deploy frontend \
            --image us-central1-docker.pkg.dev/casestudy-455411/my-repo/frontend:latest \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
